version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.0
      - image: localstack/localstack:latest
    steps:
      - checkout # check out the code in the project directory
      - run: |
          sudo apt update
          sudo apt install awscli
          pip install awsebcli --upgrade --user 
          aws configure set aws_access_key_id fake_id
          aws configure set aws_secret_access_key fake_access_key
          aws configure set default_region ap-southeast-2
          # aws --endpoint-url=http://localhost:4566 --region ap-southeast-2 s3 mb s3://test-bucket
          wget https://releases.hashicorp.com/terraform/1.0.9/terraform_1.0.9_linux_amd64.zip
          unzip terraform_1.0.9_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform --version
          terraform init
          terraform apply --auto-approve
          curl http://localhost:4566

      - run:
          command: echo "Execute your tests here :)"